FROM openproject/openproject:17.8.0@sha256:8e49371d8d2aa5b92a40231687076fa3eaa2c98ff1f4f1789e1fe9da5fd838f9
COPY --chmod=755 templates/openproject/start.sh /app/railway-start.sh
ENTRYPOINT ["/app/railway-start.sh"]
