FROM ghcr.io/almarklein/timetagger:v26.1.3@sha256:04797c616a25760ee94b352273535a516881ca820e507aee9abf7a63e5768502
COPY templates/timetagger/start.py /opt/railway/start.py
ENTRYPOINT ["python", "/opt/railway/start.py"]
