"""Ten independent, unpublished research drafts; never mutates released catalogs."""
import json, uuid
from pathlib import Path
import catalog_round3 as base
ROOT=Path(__file__).resolve().parents[1]
LOCK=json.loads((ROOT/'images.round4.lock.json').read_text())
secret,ref,private,public=base.secret,base.ref,base.private,base.public

def svc(name,**kw):
    # Resolve our own lock explicitly, leaving the released module's globals alone.
    if kw.get('image'):kw['image']=LOCK.get(kw['image'],kw['image'])
    return base.svc(name,**kw)
def pg(app,name='postgres',image='postgres:17'):
    return svc(name,image=image,volume='/var/lib/postgresql/data',env={'POSTGRES_USER':app,'POSTGRES_DB':app,'POSTGRES_PASSWORD':secret(),'PGDATA':'/var/lib/postgresql/data/pgdata','DATABASE_URL':'postgresql://'+app+':'+ref(name,'POSTGRES_PASSWORD')+'@'+ref(name,'RAILWAY_PRIVATE_DOMAIN')+':5432/'+app})
def redis():return base.redis()
def storage(buckets,exposed=False,dockerfile='shared/round4-storage/Dockerfile'):
    return svc('storage',dockerfile=dockerfile,env={'MINIO_ROOT_USER':secret(20),'MINIO_ROOT_PASSWORD':secret(),'S3_BUCKETS':buckets},volume='/data',port=9000 if exposed else None)
def gateway(name,target,port):
    return svc(name,dockerfile='shared/round4-gateway/Dockerfile',env={'UPSTREAM_HOST':ref(target,'RAILWAY_PRIVATE_DOMAIN'),'UPSTREAM_PORT':port,'ACCESS_USER':'admin','ACCESS_PASSWORD':secret()},port=8080,health='/healthz')
def dolt():
    return [svc('dolt',image='dolthub/dolt-sql-server:2.3.2',volume='/var/lib/dolt',env={'DOLT_ROOT_PASSWORD':secret(),'DOLT_ROOT_HOST':'localhost','DOLT_USER':'dolt','DOLT_USER_HOST':'%','DOLT_PASSWORD':secret(),'DOLT_DATABASE':'app','DATABASE_URL':'mysql://dolt:'+ref('dolt','DOLT_PASSWORD')+'@'+ref('dolt','RAILWAY_PRIVATE_DOMAIN')+':3306/app'})]
def seekdb():
    return [svc('seekdb',image='oceanbase/seekdb:1.4.0-100000172026082615',env={'ROOT_PASSWORD':secret(),'CPU_COUNT':2,'MEMORY_LIMIT':'2G','DATABASE_URL':'mysql://root:'+ref('seekdb','ROOT_PASSWORD')+'@'+ref('seekdb','RAILWAY_PRIVATE_DOMAIN')+':2881/test'},volume='/var/lib/oceanbase',port=2886)]
def xberg():
    return [svc('extractor',image='ghcr.io/xberg-io/xberg:1.1.2'),gateway('xberg','extractor',8000)]
def agentscope():
    return [redis(),svc('service',dockerfile='templates/agentscope/Dockerfile',env={'REDIS_HOST':ref('redis','RAILWAY_PRIVATE_DOMAIN'),'REDIS_PASSWORD':ref('redis','REDIS_PASSWORD')},volume='/data'),gateway('agentscope','service',8000)]
def marker():
    return [svc('marker',dockerfile='templates/marker/Dockerfile',env={'API_KEY':secret(),'HF_HOME':'/data/huggingface','XDG_CACHE_HOME':'/data/cache','TORCH_DEVICE':'cpu'},volume='/data'),gateway('marker-api','marker',8000)]
def fastgpt():
    db=pg('fastgpt',name='vector',image='pgvector/pgvector:0.8.0-pg15')
    mongo=svc('mongo',dockerfile='templates/fastgpt/Mongo.Dockerfile',env={'MONGO_INITDB_ROOT_USERNAME':'fastgpt','MONGO_INITDB_ROOT_PASSWORD':secret(),'MONGO_PRIVATE_HOST':ref('mongo','RAILWAY_PRIVATE_DOMAIN')},volume='/data')
    env={'PG_URL':ref('vector','DATABASE_URL'),'MONGODB_URI':'mongodb://fastgpt:'+ref('mongo','MONGO_INITDB_ROOT_PASSWORD')+'@'+ref('mongo','RAILWAY_PRIVATE_DOMAIN')+':27017/fastgpt?authSource=admin&replicaSet=rs0','DB_MAX_LINK':20,'REDIS_URL':ref('redis','REDIS_URL'),'STORAGE_VENDOR':'minio','STORAGE_REGION':'us-east-1','STORAGE_ACCESS_KEY_ID':ref('storage','MINIO_ROOT_USER'),'STORAGE_SECRET_ACCESS_KEY':ref('storage','MINIO_ROOT_PASSWORD'),'STORAGE_PUBLIC_BUCKET':'fastgpt-public','STORAGE_PRIVATE_BUCKET':'fastgpt-private','STORAGE_DOWNLOAD_URL_MODE':'short-proxy','STORAGE_S3_ENDPOINT':private('storage',9000),'STORAGE_S3_FORCE_PATH_STYLE':'true','HOSTNAME':'0.0.0.0','FE_DOMAIN':public('fastgpt'),'SYNC_INDEX':'true','LOG_ENABLE_CONSOLE':'true','LOG_CONSOLE_LEVEL':'info','LOG_ENABLE_OTEL':'false','ROOT_KEY':secret(),'DEFAULT_ROOT_PSW':(secret(),'Generated initial root password; upstream may reapply this value on restart. Keep in sync with your intended root login.'),'FILE_TOKEN_KEY':secret(),'AES256_SECRET_KEY':secret(32),'INVOKE_TOKEN_SECRET':secret(),'PLUGIN_TOKEN':secret(),'CODE_SANDBOX_TOKEN':secret(),'AIPROXY_API_TOKEN':secret(),'PLUGIN_BASE_URL':private('plugin',3000),'CODE_SANDBOX_URL':private('code-sandbox',3000),'AIPROXY_API_ENDPOINT':private('aiproxy',3000),'DATASET_PARSE_MAX_PROCESS':2,'VECTOR_MAX_PROCESS':2,'QA_MAX_PROCESS':2,'VLM_MAX_PROCESS':2}
    app=svc('fastgpt',image='ghcr.io/labring/fastgpt:v4.16.2',env=env,port=3000)
    plugin=svc('plugin',image='ghcr.io/labring/fastgpt-plugin:v1.1.2',env={**{k:ref('fastgpt',k) for k in env if k.startswith('STORAGE_') or k in ['MONGODB_URI','REDIS_URL','DB_MAX_LINK']},'AUTH_TOKEN':ref('fastgpt','PLUGIN_TOKEN')})
    sandbox=svc('code-sandbox',image='ghcr.io/labring/fastgpt-code-sandbox:v4.16.0',env={'SANDBOX_TOKEN':ref('fastgpt','CODE_SANDBOX_TOKEN'),'SANDBOX_API_MAX_BODY_MB':8,'SANDBOX_MAX_TIMEOUT':60000,'SANDBOX_MAX_MEMORY_MB':256,'SANDBOX_MAX_OUTPUT_MB':10,'SANDBOX_POOL_SIZE':2,'CHECK_INTERNAL_IP':'true','SANDBOX_REQUEST_MAX_COUNT':30})
    proxy=svc('aiproxy',image='ghcr.io/labring/aiproxy:v0.6.5',env={'ADMIN_KEY':ref('fastgpt','AIPROXY_API_TOKEN'),'SQL_DSN':ref('aiproxy-db','DATABASE_URL'),'BILLING_ENABLED':'false','DISABLE_MODEL_CONFIG':'true','LOG_DETAIL_STORAGE_HOURS':1})
    return [db,mongo,redis(),storage('fastgpt-public fastgpt-private'),pg('aiproxy',name='aiproxy-db',image='postgres:15'),app,plugin,sandbox,proxy]
def bettafish():
    env={'PYTHONUNBUFFERED':1,'STREAMLIT_SERVER_ENABLE_FILE_WATCHER':'false','DB_DIALECT':'postgresql','DB_HOST':ref('postgres','RAILWAY_PRIVATE_DOMAIN'),'DB_PORT':5432,'DB_USER':'bettafish','DB_PASSWORD':ref('postgres','POSTGRES_PASSWORD'),'DB_NAME':'bettafish','MODEL_API_KEY':(None,'Required OpenAI-compatible provider API key, shared by the report engines. Provider usage is billed separately.'),'MODEL_BASE_URL':(None,'Required OpenAI-compatible API base URL, including /v1 where your provider requires it.'),'MODEL_NAME':(None,'Required model ID supported by your provider; verify tool calling and structured output.'),'TAVILY_API_KEY':(None,'Required Tavily search API key for web research; billed separately.'),'SEARCH_TOOL_TYPE':'AnspireAPI','ANSPIRE_API_KEY':(None,'Required Anspire search API key for the upstream AnspireAPI search integration.'),'ANSPIRE_BASE_URL':'https://plugin.anspire.cn/api/ntsearch/search','HOST':'0.0.0.0','PORT':5000}
    for engine in ['INSIGHT_ENGINE','MEDIA_ENGINE','QUERY_ENGINE','REPORT_ENGINE','MINDSPIDER','FORUM_HOST','KEYWORD_OPTIMIZER']:
        for suffix,v in [('API_KEY','MODEL_API_KEY'),('BASE_URL','MODEL_BASE_URL'),('MODEL_NAME','MODEL_NAME')]:env[engine+'_'+suffix]=ref('app',v)
    return [pg('bettafish',image='postgres:15'),svc('app',dockerfile='templates/bettafish/Dockerfile',env=env,volume='/data'),gateway('bettafish','app',5000)]
def coze():
    mysql=svc('mysql',dockerfile='templates/coze-studio/MySQL.Dockerfile',env={'MYSQL_ROOT_PASSWORD':secret(),'MYSQL_DATABASE':'opencoze','MYSQL_USER':'coze','MYSQL_PASSWORD':secret()},volume='/var/lib/mysql',command='docker-entrypoint.sh mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci')
    es=svc('elasticsearch',dockerfile='templates/coze-studio/Elasticsearch.Dockerfile',env={'ES_JAVA_OPTS':'-Xms1g -Xmx1g'},volume='/bitnami/elasticsearch/data')
    etcd=svc('etcd',image='bitnamilegacy/etcd:3.5',env={'ALLOW_NONE_AUTHENTICATION':'yes','ETCD_LISTEN_CLIENT_URLS':'http://0.0.0.0:2379','ETCD_ADVERTISE_CLIENT_URLS':private('etcd',2379),'ETCD_AUTO_COMPACTION_MODE':'revision','ETCD_AUTO_COMPACTION_RETENTION':1000,'ETCD_QUOTA_BACKEND_BYTES':4294967296},volume='/bitnami/etcd')
    milvus=svc('milvus',image='milvusdb/milvus:v2.5.10',env={'ETCD_ENDPOINTS':ref('etcd','RAILWAY_PRIVATE_DOMAIN')+':2379','MINIO_ADDRESS':ref('storage','RAILWAY_PRIVATE_DOMAIN')+':9000','MINIO_BUCKET_NAME':'milvus','MINIO_ACCESS_KEY_ID':ref('storage','MINIO_ROOT_USER'),'MINIO_SECRET_ACCESS_KEY':ref('storage','MINIO_ROOT_PASSWORD'),'MINIO_USE_SSL':'false','LOG_LEVEL':'info'},volume='/var/lib/milvus',command='milvus run standalone')
    nsqlookup=svc('nsqlookupd',image='nsqio/nsq:v1.2.1',command='/nsqlookupd')
    nsqd=svc('nsqd',image='nsqio/nsq:v1.2.1',env={'LOOKUP_HOST':ref('nsqlookupd','RAILWAY_PRIVATE_DOMAIN'),'BROADCAST_HOST':ref('nsqd','RAILWAY_PRIVATE_DOMAIN')},volume='/data',command='sh -c \'exec /nsqd --data-path=/data --lookupd-tcp-address="$LOOKUP_HOST:4160" --broadcast-address="$BROADCAST_HOST"\'')
    env={'LISTEN_ADDR':':8888','WEB_LISTEN_ADDR':'0.0.0.0:8888','LOG_LEVEL':'info','SERVER_HOST':public('coze-studio'),'USE_SSL':0,'MAX_REQUEST_BODY_SIZE':33554432,'MYSQL_DSN':'coze:'+ref('mysql','MYSQL_PASSWORD')+'@tcp('+ref('mysql','RAILWAY_PRIVATE_DOMAIN')+':3306)/opencoze?charset=utf8mb4&parseTime=True','MYSQL_MAX_IDLE_CONNS':5,'MYSQL_MAX_OPEN_CONNS':30,'REDIS_ADDR':ref('redis','RAILWAY_PRIVATE_DOMAIN')+':6379','REDIS_PASSWORD':ref('redis','REDIS_PASSWORD'),'FILE_UPLOAD_COMPONENT_TYPE':'storage','STORAGE_TYPE':'minio','STORAGE_UPLOAD_HTTP_SCHEME':'https','STORAGE_BUCKET':'opencoze','MINIO_AK':ref('storage','MINIO_ROOT_USER'),'MINIO_SK':ref('storage','MINIO_ROOT_PASSWORD'),'MINIO_ENDPOINT':ref('storage','RAILWAY_PRIVATE_DOMAIN')+':9000','MINIO_API_HOST':private('storage',9000),'MINIO_USE_SSL':'false','ES_ADDR':private('elasticsearch',9200),'ES_VERSION':'v8','ES_NUMBER_OF_SHARDS':1,'ES_NUMBER_OF_REPLICAS':0,'COZE_MQ_TYPE':'nsq','MQ_NAME_SERVER':ref('nsqd','RAILWAY_PRIVATE_DOMAIN')+':4150','VECTOR_STORE_TYPE':'milvus','MILVUS_ADDR':ref('milvus','RAILWAY_PRIVATE_DOMAIN')+':19530','EMBEDDING_TYPE':'openai','OPENAI_EMBEDDING_API_KEY':None,'OPENAI_EMBEDDING_BASE_URL':'https://api.openai.com/v1','OPENAI_EMBEDDING_MODEL':'text-embedding-3-small','OPENAI_EMBEDDING_DIMS':1536,'OPENAI_EMBEDDING_REQUEST_DIMS':1536,'MODEL_PROTOCOL_0':'openai','MODEL_ID_0':None,'MODEL_NAME_0':None,'MODEL_API_KEY_0':None,'MODEL_BASE_URL_0':'https://api.openai.com/v1','MODEL_OPENCOZE_ID_0':'100001','PLUGIN_AES_AUTH_SECRET':secret(16),'PLUGIN_AES_STATE_SECRET':secret(16),'PLUGIN_AES_OAUTH_TOKEN_SECRET':secret(16)}
    backend=svc('backend',dockerfile='templates/coze-studio/Backend.Dockerfile',env=env)
    web=svc('web',dockerfile='templates/coze-studio/Web.Dockerfile',env={'BACKEND_HOST':ref('backend','RAILWAY_PRIVATE_DOMAIN'),'STORAGE_HOST':ref('storage','RAILWAY_PRIVATE_DOMAIN')})
    return [mysql,redis(),es,storage('opencoze milvus',dockerfile='templates/coze-studio/Storage.Dockerfile'),etcd,milvus,nsqlookup,nsqd,backend,web,gateway('coze-studio','web',80)]
def openrag():
    search=svc('opensearch',image='langflowai/openrag-opensearch:0.7.1',env={'discovery.type':'single-node','OPENSEARCH_INITIAL_ADMIN_PASSWORD':'Aa9!'+secret(),'OPENSEARCH_JAVA_OPTS':'-Xms1g -Xmx1g','OPENRAG_BACKEND_INTERNAL_URL':private('backend',8000),'node.store.allow_mmap':'false'},volume='/usr/share/opensearch/data')
    common={'OPENSEARCH_HOST':ref('opensearch','RAILWAY_PRIVATE_DOMAIN'),'OPENSEARCH_PORT':9200,'OPENSEARCH_USERNAME':'admin','OPENSEARCH_PASSWORD':ref('opensearch','OPENSEARCH_INITIAL_ADMIN_PASSWORD'),'OPENSEARCH_INDEX_NAME':'documents','DOCLING_SERVE_URL':private('docling',5001),'DOCLING_SERVE_VERIFY_SSL':'true','LANGFLOW_AUTO_LOGIN':'false','LANGFLOW_SUPERUSER':'admin','LANGFLOW_SUPERUSER_PASSWORD':secret()}
    backend=svc('backend',dockerfile='templates/openrag/Dockerfile',env={**common,'LANGFLOW_URL':private('langflow',7860),'LANGFLOW_PUBLIC_URL':public('langflow'),'OPENRAG_BACKEND_INTERNAL_URL':private('backend',8000),'OPENSEARCH_NODE_COUNT_CHECK_ENABLED':'false','OPENRAG_OPENSEARCH_NUMBER_OF_SHARDS':1,'OPENRAG_OPENSEARCH_NUMBER_OF_REPLICAS':0,'OPENRAG_AZURE_BLOB_ENABLED':'false','INGEST_SAMPLE_DATA':'false','OPENAI_API_KEY':None,'SESSION_SECRET':secret(),'OPENRAG_ENCRYPTION_KEY':(secret(),'Generated master secret for upstream AES-256-GCM key derivation. Preserve with backups and never rotate without a reviewed re-encryption procedure.'),'OPENRAG_ENFORCE_PREREQUISITES':'true','CORS_ALLOWED_ORIGINS':public('openrag'),'ENVIRONMENT':'production','MAX_WORKERS':1,'INSTANA_ENABLED':'false'},volume='/data')
    langflow=svc('langflow',dockerfile='templates/openrag/Langflow.Dockerfile',env={**common,'LANGFLOW_SUPERUSER_PASSWORD':ref('backend','LANGFLOW_SUPERUSER_PASSWORD'),'LANGFLOW_SECRET_KEY':secret(),'LANGFLOW_CONFIG_DIR':'/app/langflow-data','LANGFLOW_DATABASE_URL':'sqlite:////app/langflow-data/langflow.db?timeout=60','LANGFLOW_WORKERS':1,'LANGFLOW_NEW_USER_IS_ACTIVE':'false','LANGFLOW_ENABLE_SUPERUSER_CLI':'true','LANGFLOW_ALLOW_CUSTOM_COMPONENTS':'false','LANGFLOW_COMPONENTS_INDEX_PATH':'/app/flows/component_index.json','LANGFLOW_SSRF_ALLOWED_HOSTS':ref('backend','RAILWAY_PRIVATE_DOMAIN')+','+ref('docling','RAILWAY_PRIVATE_DOMAIN')+','+ref('opensearch','RAILWAY_PRIVATE_DOMAIN'),'OPENAI_API_KEY':ref('backend','OPENAI_API_KEY'),'OPENRAG_LLM_BASE_URL':private('backend',8000),'OPENSEARCH_URL':private('opensearch',9200,'https'),'LANGFLOW_LOG_LEVEL':'info'},volume='/app/langflow-data',port=7860)
    frontend=svc('frontend',image='langflowai/openrag-frontend:0.7.1',env={'OPENRAG_BACKEND_HOST':ref('backend','RAILWAY_PRIVATE_DOMAIN')})
    docling=svc('docling',image='ghcr.io/docling-project/docling-serve-cpu:latest',env={'DOCLING_SERVE_ENABLE_UI':'false','DOCLING_SERVE_MAX_NUM_CONCURRENT_JOBS':1,'HF_HOME':'/data/huggingface'},volume='/data')
    return [search,backend,langflow,frontend,docling,gateway('openrag','frontend',3000)]
def acontext():
    rabbit=svc('rabbitmq',image='rabbitmq:4-management',env={'RABBITMQ_DEFAULT_USER':'acontext','RABBITMQ_DEFAULT_PASS':secret(),'RABBITMQ_DEFAULT_VHOST':'/','RABBITMQ_NODENAME':'rabbit@localhost'},volume='/var/lib/rabbitmq')
    jaeger=svc('jaeger',image='jaegertracing/all-in-one:1.75.0',env={'COLLECTOR_OTLP_ENABLED':'true','SPAN_STORAGE_TYPE':'memory','MEMORY_MAX_TRACES':10000})
    core=svc('core',dockerfile='templates/acontext/Core.Dockerfile',env={'LLM_API_KEY':None,'LLM_BASE_URL':'https://api.openai.com/v1','LLM_SDK':'openai','LLM_SIMPLE_MODEL':'gpt-4.1','DATABASE_URL':ref('postgres','DATABASE_URL'),'REDIS_URL':ref('redis','REDIS_URL'),'MQ_URL':'amqp://acontext:'+ref('rabbitmq','RABBITMQ_DEFAULT_PASS')+'@'+ref('rabbitmq','RAILWAY_PRIVATE_DOMAIN')+':5672/%2F','S3_ENDPOINT':private('storage',9000),'S3_ACCESS_KEY':ref('storage','MINIO_ROOT_USER'),'S3_SECRET_KEY':ref('storage','MINIO_ROOT_PASSWORD'),'S3_BUCKET':'acontext-assets','S3_REGION':'us-east-1','OTEL_EXPORTER_OTLP_ENDPOINT':ref('jaeger','RAILWAY_PRIVATE_DOMAIN')+':4317','SANDBOX_TYPE':'cloudflare','CLOUDFLARE_WORKER_URL':(None,'Required URL of your separately deployed Acontext Cloudflare sandbox Worker. This template does not deploy the Worker.')})
    api=svc('api',image='ghcr.io/memodb-io/acontext-api:latest',env={'APP_ENV':'release','API_EXPORT_PORT':8029,'ROOT_API_BEARER_TOKEN':secret(),'ROOT_SECRET_PEPPER':secret(),'DATABASE_HOST':ref('postgres','RAILWAY_PRIVATE_DOMAIN'),'DATABASE_USER':'acontext','DATABASE_PASSWORD':ref('postgres','POSTGRES_PASSWORD'),'DATABASE_NAME':'acontext','DATABASE_EXPORT_PORT':5432,'REDIS_HOST':ref('redis','RAILWAY_PRIVATE_DOMAIN'),'REDIS_PASSWORD':ref('redis','REDIS_PASSWORD'),'REDIS_EXPORT_PORT':6379,'RABBITMQ_HOST':ref('rabbitmq','RAILWAY_PRIVATE_DOMAIN'),'RABBITMQ_USER':'acontext','RABBITMQ_PASSWORD':ref('rabbitmq','RABBITMQ_DEFAULT_PASS'),'RABBITMQ_VHOST':'/','RABBITMQ_VHOST_ENCODED':'%2F','RABBITMQ_EXPORT_PORT':5672,'S3_ENDPOINT':public('storage'),'S3_INTERNAL_ENDPOINT':private('storage',9000),'S3_REGION':'us-east-1','S3_ACCESS_KEY':ref('storage','MINIO_ROOT_USER'),'S3_SECRET_KEY':ref('storage','MINIO_ROOT_PASSWORD'),'S3_BUCKET':'acontext-assets','CORE_BASE_URL':private('core',8000),'OTEL_EXPORTER_OTLP_ENDPOINT':ref('jaeger','RAILWAY_PRIVATE_DOMAIN')+':4317','APP_EXTERNALURL':public('api'),'ARTIFACT_MAX_UPLOAD_SIZE_BYTES':16777216},port=8029)
    ui=svc('ui',image='ghcr.io/memodb-io/acontext-ui:latest',env={'NODE_ENV':'production','NEXT_PUBLIC_BASE_URL':public('acontext'),'NEXT_PUBLIC_BASE_PATH':'','API_SERVER_URL':private('api',8029),'ROOT_API_BEARER_TOKEN':ref('api','ROOT_API_BEARER_TOKEN'),'ROOT_SECRET_PEPPER':ref('api','ROOT_SECRET_PEPPER'),'DATABASE_URL':ref('postgres','DATABASE_URL'),'JAEGER_INTERNAL_URL':private('jaeger',16686)})
    return [pg('acontext',image='pgvector/pgvector:pg16'),redis(),rabbit,storage('acontext-assets',exposed=True),jaeger,core,api,ui,gateway('acontext','ui',3000)]
CATALOG={'fastgpt':fastgpt,'dolt':dolt,'xberg':xberg,'agentscope':agentscope,'coze-studio':coze,'bettafish':bettafish,'openrag':openrag,'marker':marker,'acontext':acontext,'seekdb':seekdb}
def generate():
    for name,factory in CATALOG.items():
        services=factory();config={'services':{str(uuid.uuid5(uuid.NAMESPACE_URL,'round4/'+name+'/'+s['name'])):s for s in services}}
        p=ROOT/'templates'/name;p.mkdir(parents=True,exist_ok=True);(p/'template.json').write_text(json.dumps(config,indent=2)+'\n');print(name,len(services))
if __name__=='__main__':generate()
