import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from catalog_round4 import CATALOG,ROOT
info={
'fastgpt':('FastGPT Core + RAG','AI/ML','labring/FastGPT','FastGPT chat, knowledge bases and workflows with MongoDB, pgvector, Redis and S3 storage.',
'Log in as root with fastgpt.DEFAULT_ROOT_PSW. Configure your model provider and embedding model in FastGPT before ingesting documents. Keep all generated encryption keys and MongoDB replica identity with your backups.',
'Nine services. Full OpenSandbox agent execution, agent previews and Docker volume management are excluded: those upstream services require a Docker socket. The separate workflow code sandbox is included. Confirm the current UI handles unavailable agent features clearly. Both S3 buckets start private; confirm signed/proxied downloads and intended public assets.',
'Build and first boot; root login; model-provider configuration; document upload and retrieval; workflow execution; authenticated replica recovery; object downloads; restart and restore. Verify MongoDB 5 lifecycle/support before release.'),
'dolt':('Dolt SQL Server','Databases','dolthub/dolt','Git-style versioned data with a private MySQL-compatible Dolt SQL server.',
'Connect from another service using dolt.DATABASE_URL. The app user has access to the app database. Root remains localhost-only. To connect from a laptop, deliberately configure a Railway TCP proxy and review transport security; none is created here.',
'One persistent service. This is a standalone database, with no DoltHub synchronization, remote backup or high availability configured. Versioned history is not an offsite backup.',
'Authenticated SQL connection; user grants; insert/commit/branch/merge; volume restart; export and restore. Verify external TLS before offering public SQL access.'),
'xberg':('Xberg / Kreuzberg Document API','AI/ML','xberg-io/xberg','CPU document extraction API from Xberg, formerly Kreuzberg, behind authenticated HTTPS.',
'Open the xberg service domain and authenticate with ACCESS_USER and ACCESS_PASSWORD. Send extraction requests according to the pinned upstream REST API documentation. The extractor stays private.',
'CPU core image, no GPU or optional full-image extras. Gateway limits request bodies to 32 MiB and upstream idle time to 600 seconds. No durable file archive is configured. API response schemas and MCP transport must be validated before advertising client compatibility.',
'Image startup; unauthorized rejection; representative PDF and Office extraction; Unicode output; MCP handshake if advertised; upload and timeout behavior.'),
'agentscope':('AgentScope Service API','AI/ML','agentscope-ai/agentscope','AgentScope API service with Redis state, persistent workspaces and authenticated access.',
'Use the agentscope domain with gateway ACCESS_USER and ACCESS_PASSWORD. Open /docs and configure model credentials and agents through the upstream API. The service uses one Uvicorn worker and an in-process message bus.',
'API-only draft: the separate upstream web UI is not bundled. Knowledge bases, default Playwright MCP, chat channels and external execution sandboxes are not enabled. LocalWorkspace tools can execute code inside this service; use one trusted owner, not untrusted tenants. Redis persists state and /data persists workspaces. Python transitive packages need a resolved dependency lock after the first build.',
'Clean build; authenticated API; provider setup; agent run and streaming; session persistence; workspace restart; restore Redis and files together; verify tool permissions and service resource limits.'),
'coze-studio':('Coze Studio','AI/ML','coze-dev/coze-studio','Coze agent and workflow studio draft with MySQL, Redis, Elasticsearch, Milvus, NSQ and object storage.',
'Enter the required model ID, display name and API key; confirm the embedding endpoint/model/dimensions. After a test deployment, review the bundled /operator/opencoze_latest_schema.hcl against MySQL and explicitly apply the required schema delta using a reviewed Atlas CLI. No startup script downloads Atlas or automatically approves schema changes. Review and run the bundled Elasticsearch setup script with --es-address http://127.0.0.1:9200 --docker-host false --index-dir /operator/es_index_schema. Only then proceed to account onboarding through the authenticated coze-studio gateway.',
'Eleven services; this is a substantial paid stack once deployed. MySQL contains the upstream initial schema; the upstream HCL delta is an explicit operator prerequisite. Elasticsearch smartcn and index templates are included; index initialization is manual. Elasticsearch, etcd, Milvus and NSQ have no application authentication in this draft and must remain private in a dedicated project. Coze storage URL rewriting, OAuth, code nodes and model integrations are unverified. No email or external plugin credentials are supplied.',
'All image builds; MySQL schema review/apply; Elasticsearch index setup; private IPv4/IPv6 connectivity; account creation; model chat; workflow run; knowledge ingestion; file signatures and downloads; NSQ delivery; volume permissions; backup and restore. Confirm legacy Bitnami images are supportable before publication.'),
'bettafish':('BettaFish Research Reports','AI/ML','666ghj/BettaFish','Multi-agent public-opinion research and report generation with PostgreSQL and persistent output files.',
'Enter MODEL_API_KEY, MODEL_BASE_URL and MODEL_NAME for an OpenAI-compatible provider, plus the selected search provider credentials. The engines reference the shared model inputs. Open the bettafish gateway using ACCESS_USER and ACCESS_PASSWORD. Set up source data before expecting database-backed insight reports.',
'The Flask orchestrator is exposed through authentication; internal engine ports remain private. Upstream frontend/engine routing must be validated in Railway, including any direct Streamlit links. Reports and logs persist under one /data volume using directory links. Social-site collection can need cookies, source-specific setup and available datasets. No assumption of automatic data availability or model/search credits.',
'Image startup; PostgreSQL schema initialization; search provider call; each engine; full report generation and download; engine routing; log retention; persistence and restore.'),
'openrag':('OpenRAG CPU Stack','AI/ML','langflow-ai/openrag','OpenRAG with OpenSearch, Langflow, CPU Docling and an authenticated frontend.',
'Enter OPENAI_API_KEY. OPENRAG_ENCRYPTION_KEY is generated for the upstream AES-256-GCM key derivation; preserve it with backups. Open the openrag gateway with its generated access credentials. Langflow has its own generated admin password, automatic login disabled and a separate authenticated public domain.',
'Six services. Backend directories are seeded into one volume; Langflow has its own database volume and image-provided flows. Railway volumes are not shared: verify API flow import and subsequent edits remain consistent across the two services. CPU Docling uses persistent model cache. No GPU, Azure emulator, OpenSearch dashboard or privileged Instana host agent is included. Some optional connectors need additional OAuth credentials. Upstream startup may run its own migrations; review these before upgrades.',
'All image builds and permissions; OpenSearch bootstrap/JWKS; authentication; Langflow key creation and flow import; document ingestion and chat; Docling model download; encryption recovery; saved connections and flows after restart; backup and restore.'),
'marker':('Marker PDF to Markdown API','AI/ML','datalab-to/marker','Authenticated, upload-only CPU Marker API for extracting Markdown from digital PDFs.',
'POST a PDF multipart field named file to /convert on marker-api. Supply gateway Basic Auth (ACCESS_USER/ACCESS_PASSWORD) plus header X-API-Key equal to marker.API_KEY. The API returns markdown and metadata. /docs requires the same credentials.',
'Custom narrow wrapper around pinned Marker: no caller-supplied filesystem paths, no original /marker route, random temporary upload filenames, deletion in finally, 32 MiB gateway limit and one conversion at a time. Fast CPU mode disables OCR; scanned PDFs and image-rich OCR workloads are not supported by this draft. Model downloads are lazy and cached in /data. Marker code and model weights have different licenses; review the upstream model-weight commercial terms, including the stated revenue/funding threshold. Python transitive dependencies require a resolved lock before release.',
'CPU image build; model download; reject missing credentials and oversized requests; adversarial filenames; digital PDF conversion; temporary-file cleanup after failure; concurrent request rejection; memory/timeout measurements; model-license review.'),
'acontext':('Acontext Agent Context Platform','AI/ML','memodb-io/Acontext','Acontext API, core and UI with PostgreSQL, Redis, RabbitMQ and S3-compatible asset storage.',
'Enter core.LLM_API_KEY and core.CLOUDFLARE_WORKER_URL for an existing Acontext sandbox Worker. Worker deployment is a separate prerequisite. Open acontext with the gateway access credentials. API clients use api.ROOT_API_BEARER_TOKEN; never put this root token into browser code.',
'Nine services. MinIO replaces upstream SeaweedFS for S3-compatible storage; bucket initialization is included. Public S3 endpoint supports signed asset URLs while the core uses the private endpoint. Jaeger is private, memory-only and capped at 10,000 traces; traces are intentionally ephemeral. Core config is an empty mapping so environment variables supply credentials. Sandbox execution cannot work until the external Worker is configured. Validate current UI/API root-token and pepper handling before release.',
'Clean image builds; DB migrations and vector extension; API auth; context/session lifecycle; worker queue processing; S3 upload and signed download; Cloudflare sandbox execution; UI login; private trace access; persistence and restore.'),
'seekdb':('OceanBase seekdb','Databases','oceanbase/seekdb','Hybrid search database with MySQL-compatible SQL, persistent data and a password-protected web console.',
'Open the seekdb domain on the provided web console and use ROOT_PASSWORD. Services in the same project connect with DATABASE_URL on private port 2881. No SQL TCP proxy is created.',
'Upstream minimum: one physical core and 2 GB memory. Draft settings use CPU_COUNT=2 and MEMORY_LIMIT=2G; configure a Railway memory limit above the database setting to leave process overhead. This is one node, without high availability, scheduled backups or additional SQL application users. Create a least-privilege SQL user for your application.',
'Container boot within resource limits; console password enforcement; private SQL connection; vector/full-text/hybrid query; volume restart; backup and restore; application-user grants.')}
metadata={};provenance={};report=['# Round 4 unpublished drafts\n','Prepared 2026-09-08. These are editor drafts, not release-certified deployments. No application projects, volumes or billable test deployments are created by this workflow.\n','All ten have concrete service configurations, pinned base images or pinned upstream source, operator inputs and release gates. Static checks do not prove runtime readiness.\n','| Draft | Services | Required operator inputs | Release gate |','|---|---:|---|---|']
for slug,factory in CATALOG.items():
 title,category,repo,description,setup,limits,gates=info[slug]
 source_slug={'xberg':'kreuzberg'}.get(slug,slug)
 src=json.loads((ROOT/'sources.round4.lock.json').read_text())[slug];provenance[slug]=src
 metadata[slug]={'name':title,'description':description,'category':category,'image':'https://github.com/'+repo.split('/')[0]+'.png'}
 config=json.loads((ROOT/f'templates/{slug}/template.json').read_text());services=list(config['services'].values());required=[];secrets=[]
 for s in services:
  for k,v in s['variables'].items():
   if 'defaultValue' not in v:required.append(s['name']+'.'+k)
   elif 'secret(' in v['defaultValue']:secrets.append(s['name']+'.'+k)
 lines=[f'# {title}\n',description+'\n','**Unpublished draft — not runtime-validated or approved for release.** Saving this template does not deploy services. Deployment later incurs Railway and provider charges.\n','## Setup\n',setup+'\n','### Deployment Dependencies\n','| Service | Source | Persistent volume | Public HTTP |','|---|---|---|---|']
 for s in services:
  source=s['source'];im=source.get('image','repository adapter: '+s.get('build',{}).get('dockerfilePath',''))
  if '@sha256:' in im:im=im.split('@')[0]+' (digest pinned)'
  mount=', '.join(x['mountPath'] for x in s.get('volumeMounts',{}).values()) or 'None'
  ports=', '.join(str(x['port']) for x in s['networking']['serviceDomains'].values()) or 'Private only'
  lines.append(f"| {s['name']} | {im} | {mount} | {ports} |")
 lines+=['\n## Required inputs\n',', '.join('`'+x+'`' for x in required) if required else 'No external secrets are required for initial configuration. Follow the setup instructions for application-level onboarding.','\nGenerated credentials: '+', '.join('`'+x+'`' for x in secrets)+'. Keep them private and preserve relevant encryption keys with backups. Every editor variable includes a description.\n','## Scope and limitations\n',limits+'\n','## Release gates\n',gates+'\n','## Operations\n','Keep database and internal service endpoints private. Railway provides HTTPS for the explicitly exposed HTTP services. Back up the listed persistent volumes and database exports, preserve encryption keys, and test a restore before relying on this instance. Review upstream migrations before upgrades. Single-volume services use one replica; no multi-region or high-availability guarantee is made. A gateway health response only proves the gateway is alive.\n','## Sources\n',f"- [Upstream project](https://github.com/{repo})",f"- [Reviewed source snapshot](https://github.com/{src['repo']}/tree/{src['commit']})",'- Image digest pins: `images.round4.lock.json` in the template source repository. Source snapshots are research references; image digests do not prove the image was built from that same commit.','- Build and runtime verification remain pending. Base-image pins do not lock packages installed by apt/apk/pip.\n']
 (ROOT/f'templates/{slug}/README.md').write_text('\n'.join(lines))
 report.append(f"| {title} | {len(services)} | {', '.join(required) or 'Application onboarding only'} | {gates} |")
(ROOT/'marketplace.round4.json').write_text(json.dumps(metadata,indent=2)+'\n')
(ROOT/'sources.round4.lock.json').write_text(json.dumps(provenance,indent=2)+'\n')
(ROOT/'DRAFTS-ROUND-4.md').write_text('\n'.join(report)+'\n')
