"""Reproduce marketplace overviews from the fifteen draft configurations."""
import json
from catalog_round6 import ROOT, CATALOG

# title, category, short description, setup, scope, acceptance workflow
INFO = {
'plunk': ('Plunk Email Platform', 'Automation', 'Email campaigns and transactional delivery with AWS SES and storage.',
'Enter core.AWS_SES_REGION, AWS_SES_ACCESS_KEY_ID, AWS_SES_SECRET_ACCESS_KEY and SES_CONFIGURATION_SET for your own SES account. Open plunk with Basic-auth username admin and plunk.ACCESS_PASSWORD, create the first application account, then set core.DISABLE_SIGNUPS=true. Configure and verify the sending domain in SES. Configure signed SNS notifications to https://YOUR-PLUNK-DOMAIN/api/webhooks/sns. API clients use the application API credential plus X-Template-Key containing the gateway password.',
'Seven services include the API/dashboard, background processes, PostgreSQL, Redis, MinIO, and protected landing/docs endpoints. Only the uploads bucket is anonymously readable, to render email images; it must never contain confidential documents. Recipient unsubscribe, preference, public-contact and SNS callback routes bypass the owner gateway and rely on upstream validation. SMTP inbound/TCP delivery is not exposed; this template is for SES-backed HTTP sending. SES production access, sending reputation, DNS and provider fees belong to the operator. AGPL-3.0 upstream terms apply.',
'Build the adapter; create the owner account; verify unauthenticated admin requests fail; send to a consented test recipient; render a stored image; process signed SNS delivery/bounce events; test one-click unsubscribe and preferences without owner credentials; confirm forged SNS messages are rejected; restart and verify campaigns, contacts and assets.'),
'bugsink': ('Bugsink Error Tracking', 'Observability', 'Self-hosted error tracking with private MySQL and generated admin access.',
'Enter bugsink.ADMIN_EMAIL. On first boot the image creates the administrator with bugsink.ADMIN_PASSWORD. Open the public Bugsink URL, sign in, create a project and copy its DSN into a test Sentry-compatible SDK. Configure optional SMTP variables for invitations and alerts.',
'Two services: Bugsink and private MySQL 8.4. Retention defaults to 30 days and 100,000 events; tune after measuring your workload. No separate event volume is used: back up MySQL. The upstream PolyForm Shield license has restrictions; this listing does not grant rights to offer a competing hosted service. SDK ingestion is intentionally public and uses the application DSN.',
'Fresh database initialization; admin login; ingest a test exception through the actual SDK; view the stack trace; process queued events; confirm application registration policy; send one test alert; check retention; restart and restore the database into a separate instance.'),
'notifuse': ('Notifuse Email Marketing', 'Automation', 'Email campaigns with PostgreSQL and a protected first-run setup.',
'Enter core.ROOT_EMAIL and configure SMTP delivery for login/setup email. Open /setup on the Notifuse domain using username admin and notifuse.ACCESS_PASSWORD. Complete the initial setup for ROOT_EMAIL, create a workspace, and configure its sending provider. SMTP credentials and a verified sender must be yours.',
'Three services: core, PostgreSQL and gateway. Setup routes are owner-protected; native app authentication protects normal APIs while tracking and provider callbacks remain reachable. PostgreSQL is a dedicated cluster because Notifuse creates workspace databases. v40 uses the upstream Business Source License and the free self-host tier is limited to three workspaces. Paid permissions, SES tenant features, SSO and multilingual variants are not unlocked; NOTIFUSE_LICENSE_KEY is optional and operator supplied.',
'Fresh wizard access and anonymous setup rejection; login email; workspace creation and separate database; send a test campaign; exercise unsubscribe, tracking and provider callbacks without gateway credentials; check free-tier limits; preserve SECRET_KEY and restore every workspace database.'),
'lago': ('Lago Usage Billing', 'Automation', 'Usage billing with PostgreSQL, Redis, background jobs and invoice PDFs.',
'Enter api.LAGO_ORG_USER_EMAIL. The migration task creates the organization using LAGO_ORG_USER_PASSWORD and LAGO_ORG_API_KEY before opening the API. Open lago and sign in. Configure billing currency, plans, a test customer and optional SMTP. Integrate payment-provider credentials inside Lago only when needed.',
'Five services. The API adapter supervises the API, Sidekiq worker and clock in one service so the RSA key and local file storage share /data. PostgreSQL partman, Redis and PDF rendering are private; frontend and authenticated API are public. General signup and the Sidekiq web UI are disabled. Preserve all encryption variables and /data/keys/private.pem. Upstream AGPL-3.0 applies to community code; enterprise features and payment-provider accounts are not included. Invoice correctness and jurisdiction-specific billing setup are the operator\'s responsibility.',
'Build and run upstream migration scripts; verify owner seeding is idempotent; configure a usage metric and plan; ingest a test event; generate and download an invoice PDF; confirm jobs and clock run; test webhook delivery; restart without changing keys; restore the database and file volume together.'),
'docuseal': ('DocuSeal Document Signing', 'Automation', 'Document signing with PostgreSQL and an administrator created at startup.',
'Enter docuseal.ADMIN_EMAIL. First startup creates the account and administrator with ADMIN_PASSWORD before HTTP begins. Sign in, set the organization details and SMTP sender, upload a test PDF and create a signing template. Share a test signing link with a recipient you control.',
'Two services: DocuSeal and PostgreSQL. Uploaded documents and generated artifacts are persisted in /data/docuseal; account data is in PostgreSQL. The bootstrap does not reset an existing account or password. Recipient links use native application authorization and need no gateway password. Preserve SECRET_KEY_BASE and the database-backed signing certificates. Review upstream AGPL-3.0 plus LICENSE_ADDITIONAL_TERMS; no paid license or legal compliance certification is included.',
'Build; verify automatic migrations and one-time admin creation; reject an anonymous setup takeover; upload a PDF; place fields; complete a signature as the test recipient; download the signed PDF and audit evidence; test SMTP; restart and restore database plus documents and keys.'),
'frappe-learning': ('Frappe Learning', 'Other', 'Learning management with Frappe, MariaDB, Redis and persistent courses.',
'Open frappe-learning and sign in as Administrator with ADMIN_PASSWORD. A single site is created automatically. Configure outgoing email, create an instructor and learner, then publish a test course. Payments is installed as the upstream LMS dependency; payment-provider credentials are configured separately.',
'Three services. The adapter builds LMS v2.63.0 and Payments at recorded commits on the pinned Frappe framework image. It runs web, Socket.IO, queue worker and scheduler with one /data volume. Database and Redis are private. AGPL-3.0 applies to LMS. The framework/app build and dependency compatibility still require a real image build. Upgrades to an existing site require a backup followed by ALLOW_MIGRATION=true; reset it after validation. Paid course billing requires a supported external payment provider.',
'Build LMS and Payments; create a clean site; verify Administrator login; create a course with a file lesson and quiz; enroll a learner and record completion; test realtime/worker jobs and email; verify Payments installation; restart; use bench backups and prove recovery of database, site config, public and private files.'),
'db-gpt': ('DB-GPT Data Assistant', 'AI/ML', 'Private AI data assistant with persistent metadata and vector storage.',
'Enter core.OPENAI_API_KEY. Set OPENAI_API_BASE, LLM_MODEL_NAME and embedding settings if using a compatible provider. Open db-gpt with username admin and db-gpt.ACCESS_PASSWORD. Add a small test dataset and a database connection with narrowly scoped read permissions.',
'Two services: DB-GPT and an owner gateway. SQLite metadata, Chroma vectors, uploaded data and model caches persist below /data. This is a trusted-owner CPU deployment using external LLM/embedding APIs; GPU inference, a Docker socket and a separate execution sandbox are not provisioned. Generated ENCRYPTION_KEY must survive recovery. Provider fees are separate. MIT upstream license. Extra database connectors may need additional drivers; arbitrary connector coverage is not claimed.',
'Build; reject anonymous UI/API access; use an actual model request; upload and retrieve a document; ask a query against a disposable read-only database; verify SQL review behavior and connector support; confirm persistent metadata and vectors after restart; back up and restore /data and ENCRYPTION_KEY.'),
'frappe-insights': ('Frappe Insights', 'Analytics', 'Business intelligence dashboards with Frappe, MariaDB and Redis.',
'Open frappe-insights and sign in as Administrator with ADMIN_PASSWORD. Connect a disposable read-only analytics datasource, create a query and save a dashboard. Configure SMTP for collaboration. Restrict datasource credentials to the data your users should see.',
'Three services. Builds Insights v3.13.2 at its recorded commit on the pinned framework. Web, Socket.IO, worker and scheduler share one site volume. Server scripts are enabled because Insights needs them; treat application administrators as trusted. External analytics databases are not copied into this stack or included in its backups. AGPL-3.0 upstream terms apply. Test compatibility with your chosen connector; paid managed hosting and enterprise support are not included.',
'Build all frontend and Python dependencies; fresh site installation; login; connect the selected database; execute a bounded query; save and share a dashboard; verify viewer permissions; scheduled refresh and worker processing; restart; restore site data and reconnect the read-only source.'),
'frappe-builder': ('Frappe Builder', 'CMS', 'Visual website builder with Frappe, MariaDB and persistent assets.',
'Open frappe-builder and sign in as Administrator with ADMIN_PASSWORD. Create a page, upload an asset and publish it. Configure a custom Railway domain and update PUBLIC_URL if using your own hostname. SMTP and optional AI-provider credentials are configured separately.',
'Three services. Builds Builder v1.34.0 at its recorded commit on the pinned framework. Admin/editor authentication is native Frappe, so published pages can be public. One site and one replica; custom domain/DNS setup is not automated. The Builder application is MIT-licensed; framework and dependency licenses still apply. Build compatibility and rendered custom-domain links need runtime checks. Backups must include MariaDB plus /data site configuration and assets.',
'Build Python and frontend assets; create a fresh site; sign in; edit and preview a page; upload an image; publish and open it logged out; verify editor remains protected; test asset URLs and custom host redirects; restart and restore the page and files.'),
'unla': ('Unla MCP Gateway', 'AI/ML', 'MCP gateway and management UI with persistent SQLite and owner access.',
'Open unla using gateway username admin and unla.ACCESS_PASSWORD. Sign into the application using core.SUPER_ADMIN_USERNAME and SUPER_ADMIN_PASSWORD. Register a harmless remote HTTP tool and connect an MCP client. Clients send X-Template-Key with the gateway password alongside any native Authorization credential.',
'Two services. The pinned all-in-one image runs UI, API and MCP gateway; SQLite persists at /app/data/unla.db. The whole public origin is owner-protected. The inner proxy forwards streaming responses and WebSocket upgrades. Remote clients must support the additional header; a bare URL will not bypass the owner gate. OAuth/session behavior follows upstream defaults and must be verified across restarts; this is not a multi-replica topology. MIT upstream license.',
'Build; verify both gateway and application login; register and invoke an HTTP-backed tool; exercise SSE/streamable HTTP and WebSocket paths; reject missing/incorrect owner keys; verify native Bearer auth passes through; restart and verify gateway configuration and session behavior; restore SQLite.'),
'mcpjungle': ('MCPJungle Enterprise Mode', 'AI/ML', 'MCP registry and gateway with PostgreSQL and a protected initialization.',
'Open mcpjungle with username admin and mcpjungle.ACCESS_PASSWORD. Initialize once by sending POST /init with JSON {"mode":"enterprise"} and X-Template-Key set to ACCESS_PASSWORD. Save the returned admin_access_token securely; never put it in template defaults or logs. Use that token for subsequent native API authorization, retaining X-Template-Key for gateway access.',
'Three services: MCPJungle, PostgreSQL and owner gateway. Upstream enterprise mode is a server authorization mode, not a bundled commercial license. The uninitialized service is private behind the owner gate. The standard distroless image supports the included runtime; arbitrary local stdio programs and host-shell tools are not installed. Prefer remote HTTP MCP servers. Mozilla Public License 2.0 upstream terms apply. Client tooling must support the additional header.',
'Fresh database; anonymous init rejection; initialize and securely capture the admin token; confirm repeat initialization cannot seize ownership; register a remote test server; discover and invoke a tool; verify permission rejection and streaming; restart without losing registry/users; restore PostgreSQL.'),
'perses': ('Perses Dashboards', 'Observability', 'Observability dashboards with persistent storage and owner access.',
'Open perses using username admin and perses.ACCESS_PASSWORD. Add a project, configure a reachable Prometheus-compatible datasource and create a dashboard. Keep datasource credentials private and use read-only access where possible.',
'Two services. Perses runs privately with native auth disabled and every public application route protected by the owner gateway. This is a shared-owner workspace, not per-user RBAC. File database and extracted plugins persist on /data; ENCRYPTION_KEY must remain exactly 32 alphanumeric characters and be preserved with backups. Upstream plugin archives are included. This template does not collect or store metrics itself; supply a datasource. Apache-2.0 upstream license.',
'Build and extract the packaged plugins; reject anonymous requests; create a datasource and query real metrics; save/reload a dashboard; verify plugin assets load; restart with encrypted datasource credentials intact; restore /data with the same encryption key.'),
 'timetagger': ('TimeTagger', 'Other', 'Personal time tracking with generated credentials and persistent data.',
'Open timetagger and sign in using ADMIN_USERNAME (admin by default) and ADMIN_PASSWORD. The startup adapter generates a bcrypt credential from that password without writing its plaintext to a file. Create a few time records and tags, then view a report.',
'One service with persistent /opt/_timetagger storage. This draft provisions one configured account, not a team subscription/billing system. Change ADMIN_PASSWORD in Railway to rotate the configured credential; keep it at least 16 characters and no more than 72 UTF-8 bytes. TimeTagger uses the GPL-3.0 license. Railway usage is separate from the upstream service.',
'Build; validate bcrypt dependency and native login; reject a wrong password; create and edit time records; check tags and report totals; test browser sync; restart without record loss; restore the data volume; verify a credential rotation.'),
'vespa': ('Vespa Search Starter', 'Storage', 'Single-node search with a starter document schema and protected API.',
'Open the vespa endpoint using username admin and vespa.ACCESS_PASSWORD, or send X-Template-Key for API calls. The first boot installs the included title/body search schema. Feed a document of type document to /document/v1/default/document/docid/ID and query /search/. The configuration API on port 19071 stays private; deploy schema changes from within the project.',
'Two services: one Vespa node and an owner gateway. Data persists at /opt/vespa/var. The starter package is deployed only once; a marker prevents redeploys from overwriting an operator schema. This is a single-node example with no replication or high availability. Allocate sufficient memory/CPU for Vespa and measure it; no low-cost monthly estimate is provided. Runtime startup, hostname mapping and application activation still require verification. Apache-2.0 upstream license.',
'Build; wait for configuration health and starter activation; reject anonymous feed/query operations; feed a title/body document and retrieve it; run a BM25 query; restart and verify data; deploy an intentional schema revision privately; confirm redeploy does not reset it; test backup and restore.'),
'agenta': ('Agenta LLM Engineering', 'AI/ML', 'LLM evaluation and tracing with databases, workers and object storage.',
'Enter runner.AGENTA_RUNNER_DAYTONA_API_KEY for your own Daytona account. Open agenta using gateway username admin and agenta.ACCESS_PASSWORD, then create the application account. Configure a model provider in Agenta. External SDK calls require X-Template-Key with the gateway password in addition to the native API key; confirm your client supports this.',
'Thirteen services adapted from the upstream Railway OSS layout: PostgreSQL, Redis, SeaweedFS 4.37, web/mobile, API/services/runner, two workers, cron, Supertokens and gateway. API migrations gate background startup, and its signing key persists on /data. SeaweedFS is pinned to the upstream-required STS-compatible version. Runner execution uses external Daytona; host Docker/FUSE is unavailable. No model or sandbox credits, enterprise features, HA or fixed hosting cost are included. The OSS code is MIT-licensed; enterprise code has separate terms. This is the largest and highest-validation-effort draft in this batch.',
'Build adapters; initialize all three databases; run core/tracing migrations; verify worker readiness; sign up and sign in through Supertokens; evaluate a prompt; ingest and view a trace; save and retrieve a stored artifact via STS; run a small Daytona task; verify native API auth plus owner header; restart all roles; restore databases, SeaweedFS and signing/encryption keys together.'),
}

def main():
 metadata={}
 sources=json.loads((ROOT/'sources.round6.lock.json').read_text())
 for slug, factory in CATALOG.items():
  title,category,description,setup,scope,acceptance=INFO[slug]
  src=sources[slug]
  metadata[slug]={'name':title,'description':description,'category':category,'image':'https://github.com/'+src['repo'].split('/')[0]+'.png'}
  services=factory()
  lines=[f'# Deploy and Host {title} on Railway\n',description+'\n',
   '**Unpublished draft. Image builds and Railway application workflows have not been validated.** The template defines services; saving a draft creates no running application. Deploying it later incurs Railway usage and any external provider charges.\n',
   f'## About Hosting {title}\n',scope+'\n','## Setup\n',setup+'\n',
   '### Deployment Dependencies\n','| Service | Source | Persistent volume | Public HTTP port |','| --- | --- | --- | --- |']
  for s in services:
   source=s['source'].get('image','Repository adapter: '+s.get('build',{}).get('dockerfilePath','')).split('@sha256:')[0]
   volume=', '.join(v['mountPath'] for v in s.get('volumeMounts',{}).values()) or 'None'
   ports=', '.join(str(v['port']) for v in s['networking']['serviceDomains'].values()) or 'Private'
   lines.append(f"| {s['name']} | {source} | {volume} | {ports} |")
  lines+=['\n## Operator inputs\n','| Variable | Requirement |','| --- | --- |']
  credentials=[]
  for s in services:
   for k,v in s['variables'].items():
    if 'defaultValue' not in v:
     lines.append(f"| `{s['name']}.{k}` | {'Optional. ' if v.get('isOptional') else 'Required. '}{v['description']} |")
    elif 'secret(' in v['defaultValue']:credentials.append(f"`{s['name']}.{k}`")
  if not any('defaultValue' not in v for s in services for v in s['variables'].values()):lines.append('| None | Initial credentials are generated; complete application setup above. |')
  lines+=['\nGenerated credentials: '+', '.join(credentials)+'. Never copy another deployment\'s secrets. Preserve encryption/signing keys with backups.\n',
   f'## Why Deploy {title} on Railway\n','The definition connects private dependencies, declares persistent volumes and exposes the listed application endpoints through Railway HTTPS. Repository adapters build from `codex/fifteen-template-drafts` with the repository root as Docker context. Configure one replica for each stateful service.\n',
   '## Common Use Cases\n',description+' Use a separate test project to verify the workflow below before putting real data into the instance.\n',
   f'## Dependencies for {title}\n',f"Reviewed upstream release: [{src['tag']}](https://github.com/{src['repo']}/tree/{src['sha']}). Image digests are recorded in `images.round6.lock.json`; source receipts are in `sources.round6.lock.json`. A matching version label does not independently prove image-to-source provenance. Base-image pins do not lock later apt/apk or language-package resolution.\n",
   '## Recommended acceptance checks\n',acceptance+'\n',
   '## Operations and recovery\n','Back up every listed persistent volume and export every application database, preserving the generated encryption/signing secrets. Restore into a separate test instance and repeat the functional workflow before relying on the backup. Keep internal databases private. An owner gateway `/healthz` response proves only that gateway is alive, not that its application or dependencies are ready. After changing a public domain, update all application origin and callback settings. Review upstream migrations before upgrading; record the old source/image pins and a recoverable backup. No scheduled backup service is configured by this draft.\n',
   '## Validation status\n','The checked-in catalog supports static pin, reference, Docker COPY-path and script-syntax validation. Container builds, native proxy behavior, fresh Railway deployment, provider integrations, persistence and restore remain release gates. See `DRAFTS-ROUND-6.md` for the batch record.\n']
  (ROOT/'templates'/slug/'README.md').write_text('\n'.join(lines))
 (ROOT/'marketplace.round6.json').write_text(json.dumps(metadata,indent=2)+'\n')
 print('Wrote 15 marketplace overviews and metadata records')

if __name__=='__main__':main()
