"""Deployment-facing descriptions for every generated Railway variable."""
DESCRIPTIONS = {
    'PORT': 'HTTP port inside this service. Keep the default to match its Railway public port and health check.',
    'HOST': 'HTTP bind address. Keep 0.0.0.0 so Railway can reach the service.',
    'HOSTNAME': 'Application bind address. Keep 0.0.0.0 for container networking.',
    'NODE_ENV': 'Node.js runtime mode. Keep production for hosted deployments.',
    'ENV': 'Firecrawl runtime mode. Keep local for this self-hosted deployment.',
    'RAILWAY_DOCKERFILE_PATH': 'Repository-relative Dockerfile used to build this service. Keep the supplied path.',
    'POSTGRES_USER': 'PostgreSQL initialization user, or the matching connection user for the private database.',
    'POSTGRES_DB': 'Initial PostgreSQL database name, or the matching database selected by the application.',
    'POSTGRES_PASSWORD': 'PostgreSQL password. Generated for the database and referenced by dependent services; keep private.',
    'POSTGRES_HOST': 'Private PostgreSQL hostname. Automatically resolved from the postgres service.',
    'POSTGRES_PORT': 'Private PostgreSQL TCP port. Keep 5432.',
    'PGDATA': 'PostgreSQL data directory within the persistent volume. Do not change on an existing database.',
    'APP_DB': 'Application database created during first initialization of an empty PostgreSQL volume.',
    'APP_USER': 'Dedicated application database role created during first initialization.',
    'APP_PASSWORD': 'Generated password for the application database role. Preserve it with your backups.',
    'ALLOW_APP_DATABASE_CREATION': 'Grant database and role creation privileges required by ToolJet. Keep false for other applications.',
    'ENABLE_VECTOR': 'Initialize the pgvector extension for applications that require vector storage. Keep the supplied value.',
    'DATABASE_URL': 'Private PostgreSQL connection URL assembled from generated credentials and service references. No manual value is needed.',
    'REDIS_PASSWORD': 'Generated private Redis/Valkey password, or a reference to that password. Keep secret.',
    'REDIS_URL': 'Private authenticated Redis/Valkey connection URL. Automatically assembled from service references.',
    'REDIS_HOST': 'Private Redis/Valkey hostname supplied by the redis service reference.',
    'REDIS_PORT': 'Private Redis/Valkey port. Keep 6379.',
    'REDIS_RATE_LIMIT_URL': 'Private Redis URL used for Firecrawl rate limiting. References the authenticated redis service.',
    'API_KEY': 'Generated API authentication key, or a reference to the shared internal API key. Keep private and preserve matching references.',
    'UPSTREAM_URL': 'Private Firecrawl API URL used by the public gateway. Keep the api service reference.',
    'ALLOW_LOCAL_WEBHOOKS': 'Allow webhook requests to local/private targets. Keep false to restrict access to internal networks.',
    'BLOCK_MEDIA': 'Block browser media downloads to reduce resource usage during scraping.',
    'BROWSER_POOL_SIZE': 'Firecrawl browser pool size. Starts at 2; increase only after measuring memory use.',
    'MAX_CONCURRENT_PAGES': 'Maximum concurrent renderer pages. Starts at 2 to limit browser memory usage.',
    'MAX_CONCURRENT_JOBS': 'Maximum simultaneous Firecrawl jobs. Increase only when memory and queue latency permit.',
    'CRAWL_CONCURRENT_REQUESTS': 'Concurrent requests per crawl. Starts at 2; respect target-site rate limits.',
    'NUM_WORKERS_PER_QUEUE': 'Workers per Firecrawl queue. Increase after measuring CPU, memory, and queue latency.',
    'BULL_AUTH_KEY': 'Generated secret protecting Firecrawl queue administration. Keep private.',
    'USE_DB_AUTHENTICATION': 'Internal Firecrawl database authentication toggle. Keep false with this private API and authenticated public gateway.',
    'WORKER_PORT': 'Internal Firecrawl worker HTTP port. Keep the supplied port and do not expose it publicly.',
    'EXTRACT_WORKER_PORT': 'Internal extraction-worker port. Keep the supplied port and leave it private.',
    'HARNESS_STARTUP_TIMEOUT_MS': 'Maximum Firecrawl harness startup wait in milliseconds. Increase if cold starts need more time.',
    'PLAYWRIGHT_MICROSERVICE_URL': 'Private browser renderer scrape endpoint. Automatically references the browser service.',
    'NUQ_RABBITMQ_URL': 'Private RabbitMQ connection URL for the NuQ queue, using generated broker credentials.',
    'RABBITMQ_DEFAULT_USER': 'RabbitMQ user created on first initialization. Keep aligned with the NuQ connection URL.',
    'RABBITMQ_DEFAULT_PASS': 'Generated RabbitMQ password. Preserve it with the persistent broker data.',
    'RABBITMQ_NODENAME': 'Stable RabbitMQ node identity for persisted queue data. Keep rabbit@localhost across redeployments.',
    'AFFINE_INDEXER_ENABLED': 'AFFiNE indexer toggle. Disabled in this deployment; enabling it requires separate upstream setup.',
    'AFFINE_SERVER_EXTERNAL_URL': 'Public AFFiNE HTTPS URL. Generated from the Railway domain; update when assigning a custom domain.',
    'AFFINE_SERVER_HOST': 'AFFiNE bind address. Keep 0.0.0.0 for container networking.',
    'AFFINE_SERVER_PORT': 'AFFiNE HTTP port. Keep aligned with PORT and Railway networking.',
    'WEBAPP_URL': 'Public Formbricks HTTPS URL. Update together with NEXTAUTH_URL when changing domains.',
    'NEXTAUTH_URL': 'Public authentication callback base URL. Keep equal to WEBAPP_URL.',
    'NEXTAUTH_SECRET': 'Generated authentication signing secret. Preserve across restarts and backup restores.',
    'ENCRYPTION_KEY': 'Generated Formbricks encryption key. Back it up securely; changing it can make encrypted data unreadable.',
    'CRON_SECRET': 'Generated secret authorizing Formbricks scheduled maintenance endpoints. Keep private.',
    'HUB_API_KEY': 'Generated authentication key shared with the private Hub service. Keep the service references aligned.',
    'HUB_API_URL': 'Private Hub API base URL. Automatically references the hub service.',
    'CUBEJS_API_SECRET': 'Shared generated Cube analytics signing secret. Preserve the matching app and Cube references.',
    'CUBEJS_API_URL': 'Private Cube analytics API URL. Automatically references the cube service.',
    'CUBEJS_JWT_ISSUER': 'Expected issuer for Formbricks analytics tokens. Keep the app and Cube values identical.',
    'CUBEJS_JWT_AUDIENCE': 'Expected audience for Formbricks analytics tokens. Keep the app and Cube values identical.',
    'CUBEJS_DB_TYPE': 'Cube database driver. Keep postgres for this deployment.',
    'CUBEJS_DB_HOST': 'Private PostgreSQL hostname used by Cube analytics.',
    'CUBEJS_DB_NAME': 'Formbricks database queried by Cube analytics.',
    'CUBEJS_DB_USER': 'Application database role used by Cube analytics.',
    'CUBEJS_DB_PASS': 'Reference to the generated application database password used by Cube.',
    'CUBEJS_DB_PORT': 'Private PostgreSQL port used by Cube. Keep 5432.',
    'CUBEJS_DEFAULT_API_SCOPES': 'Cube API scopes enabled for analytics requests. Keep the upstream-compatible default.',
    'CUBEJS_EXTERNAL_DEFAULT': 'Cube external pre-aggregation storage toggle. Keep the supplied default for this topology.',
    'CUBEJS_CACHE_AND_QUEUE_DRIVER': 'Cube cache/queue driver. Uses memory in this single-service deployment.',
    'EMAIL_VERIFICATION_DISABLED': 'Email verification is initially disabled. Set to 0 only after configuring and testing SMTP delivery.',
    'PASSWORD_RESET_DISABLED': 'Password reset is initially disabled. Set to 0 after configuring and testing SMTP delivery.',
    'TELEMETRY_DISABLED': 'Disable application telemetry. Keep 1 to retain this privacy default.',
    'OPENPROJECT_HOST__NAME': 'Public OpenProject hostname without a scheme. Update when assigning a custom domain.',
    'OPENPROJECT_HTTPS': 'Generate HTTPS application URLs behind Railway TLS termination. Keep true.',
    'OPENPROJECT_HSTS': 'Enable HTTP Strict Transport Security for the public HTTPS deployment.',
    'OPENPROJECT_SEED__ADMIN__USER__PASSWORD': 'Generated initial password for the admin account. Read it after deployment, sign in, and change it promptly.',
    'OPENPROJECT_SEED__ADMIN__USER__PASSWORD__RESET': 'Require the seeded administrator to change the initial password at first login.',
    'OPENPROJECT_COLLABORATIVE__EDITING__HOCUSPOCUS__URL': 'Public secure WebSocket URL for collaborative editing. Update with the application domain.',
    'PG_STARTUP_WAIT_TIME': 'Time allowed for PostgreSQL startup before OpenProject initialization. Keep the supplied default unless startup logs require more time.',
    'RAILS_MAX_THREADS': 'Maximum Rails request threads. Tune with available memory and database capacity.',
    'RAILS_MIN_THREADS': 'Minimum Rails request threads. Keep at or below RAILS_MAX_THREADS.',
    'SECRET_KEY_BASE': 'Generated application signing secret. Preserve across restarts and backup restores.',
    'TOOLJET_HOST': 'Public ToolJet HTTPS URL. Automatically generated; update for a custom domain.',
    'TOOLJET_EDITION': 'ToolJet edition selector. Keep ce for this Community Edition image.',
    'ENABLE_TOOLJET_DB': 'Enable the built-in ToolJet Database backed by the private PostgreSQL and PostgREST services.',
    'TOOLJET_DB_RECONFIG': 'Enable ToolJet Database configuration for the selected upstream startup flow. Keep the supplied value.',
    'TOOLJET_DB': 'Database name for built-in ToolJet Database storage.',
    'TOOLJET_DB_HOST': 'Private PostgreSQL hostname for ToolJet Database.',
    'TOOLJET_DB_PORT': 'Private PostgreSQL port for ToolJet Database. Keep 5432.',
    'TOOLJET_DB_USER': 'Dedicated PostgreSQL application role used for ToolJet Database.',
    'TOOLJET_DB_PASS': 'Reference to the generated PostgreSQL application password for ToolJet Database.',
    'TOOLJET_DB_SSL': 'PostgreSQL TLS toggle for ToolJet Database. The default uses Railway private networking.',
    'PG_HOST': 'Private PostgreSQL hostname for ToolJet application metadata.',
    'PG_PORT': 'Private PostgreSQL port for ToolJet application metadata. Keep 5432.',
    'PG_USER': 'Dedicated PostgreSQL application role used by ToolJet.',
    'PG_PASS': 'Reference to the generated PostgreSQL application password used by ToolJet.',
    'PG_DB': 'Database name for ToolJet application metadata.',
    'PG_SSL': 'PostgreSQL TLS toggle for ToolJet metadata. The default uses Railway private networking.',
    'PGRST_DB_URI': 'Private PostgreSQL connection URL used by PostgREST for ToolJet Database.',
    'PGRST_DB_PRE_CONFIG': 'Upstream ToolJet pre-configuration function invoked by PostgREST. Keep the supplied function name.',
    'PGRST_HOST': 'Private PostgREST base URL. Automatically references the postgrest service.',
    'PGRST_SERVER_PORT': 'Private PostgREST HTTP port. Keep aligned with the ToolJet reference.',
    'PGRST_JWT_SECRET': 'Generated JWT secret shared between ToolJet and PostgREST. Preserve matching references and keep private.',
    'LOCKBOX_MASTER_KEY': 'Generated encryption key for saved ToolJet data-source credentials. Preserve securely with database backups.',
    'TOOLJET_QUEUE_DASH_PASSWORD': 'Generated password for ToolJet queue administration. Keep private.',
    'TOOLJET_WORKFLOW_SANDBOX_BYPASS': 'Python sandbox bypass. Keep false; this template does not advertise Python workflow execution support.',
    'WORKER': 'Enable the ToolJet background worker in the application service.',
    'SERVE_CLIENT': 'Serve the ToolJet web client from the application service.',
    'SMTP_DISABLED': 'SMTP starts disabled. Configure upstream SMTP settings and enable delivery before using invitations or password resets.',
    'DISABLE_TOOLJET_TELEMETRY': 'Disable ToolJet telemetry. Keep the supplied privacy default.',
}
for alias, key in {'REDIS_SERVER_HOST':'REDIS_HOST','REDIS_SERVER_PORT':'REDIS_PORT','REDIS_SERVER_PASSWORD':'REDIS_PASSWORD'}.items():
    DESCRIPTIONS[alias] = DESCRIPTIONS[key]
